name: DevOps CI

on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start application
        run: |
          APP_NAME="CI Test App" APP_VERSION="test" python3 server.py &
          sleep 2

      - name: Test application
        run: curl -f http://127.0.0.1:8000

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/ashok-gumma/devops-app:latest .
      - name: Push Docker imagex
        run: docker push ghcr.io/ashok-gumma/devops-app:latest
